In [29]:
import tweepy
import pandas as pd
auth = tweepy.OAuthHandler("mHwDkHtAr0YsmrJhuVpA9MQhH", "8OXET1pwHp70H1R5Ed0w9NEeBXrZVJOqa9JLbgEtO6xjLq8OlV")
auth.set_access_token("1384514435385937926-ufOKI9oTRQrM0ibYTpRBDIuR7klIYC", "0NNpZ0zPHWylv7p6MLPwjoZPuCZsqHXsbBNS00GElwfTX")
api = tweepy.API(auth)

In [30]:
me = api.me()
me.screen_name

'Chelsea49123764'

In [63]:
def extract_timeline_as_df(timeline_list):
    columns = set() # set items have to be unique, rather than a list
    allowed_types = [str,int]
    tweet_data = []
    for status in timeline_list:
    #     print(status.text)
    #     print(vars(status)) # print out a dictionary
        status_dict = dict(vars(status))
        keys = status_dict.keys()
        single_tweet_data = {"user": status.user.screen_name, "author": status.author.screen_name}
        for k in keys:
            v_type = type(status_dict[k])
            if v_type in allowed_types:
                single_tweet_data[k] = status_dict[k]
                columns.add(k)

        tweet_data.append(single_tweet_data)

    header_cols = list(columns)
    header_cols.append("user")
    header_cols.append("author")
    df = pd.DataFrame(tweet_data, columns=header_cols)
    return df

In [56]:
my_timeline = api.home_timeline()

In [60]:
df2 = extract_timeline_as_df(my_timeline)
df2

,lang,text,retweet_count,source,id_str,favorite_count,source_url,id,user,author
0,en,Hi there,0,Twitter Web App,1384828390864084993,0,https://mobile.twitter.com,1384828390864084993,Chelsea49123764,Chelsea49123764
1,en,testing,0,Twitter Web App,1384828363307511814,0,https://mobile.twitter.com,1384828363307511814,Chelsea49123764,Chelsea49123764

In [67]:
# extract other user timeline
user = api.get_user("code")
user_timeline = user.timeline()
df3 = extract_timeline_as_df(user_timeline)
df3.head()

,lang,text,in_reply_to_user_id,in_reply_to_status_id,retweet_count,in_reply_to_status_id_str,quoted_status_id,source,id_str,favorite_count,in_reply_to_screen_name,source_url,quoted_status_id_str,id,in_reply_to_user_id_str,user,author
0,en,RT @msdevCA: Microsoft Senior Software Enginee...,NaN,NaN,13,NaN,NaN,Twitter Web App,1384597048310177797,0,NaN,https://mobile.twitter.com,NaN,1384597048310177797,NaN,code,code
1,en,To all C++ devs ðŸ’» CMakePresets.json support is...,NaN,NaN,15,NaN,1.384546e+18,Buffer,1384572074941878273,92,NaN,https://buffer.com,1384546094391037962,1384572074941878273,NaN,code,code
2,en,RT @davorabbit: This is super cool! The widget...,NaN,NaN,9,NaN,1.383334e+18,Buffer,1384533824017678339,0,NaN,https://buffer.com,1383333912470974470,1384533824017678339,NaN,code,code
3,en,"RT @dzhavatushev: I'm humbled to see my ""CSS F...",NaN,NaN,49,NaN,NaN,Buffer,1384265807786512390,0,NaN,https://buffer.com,NaN,1384265807786512390,NaN,code,code
4,en,RT @_tanhakabir: REST Book is published on the...,NaN,NaN,33,NaN,NaN,Buffer,1384210207639621642,0,NaN,https://buffer.com,NaN,1384210207639621642,NaN,code,code